
services:
  postgres:
    image: postgres:15-alpine
    container_name: db_clientes
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: db_clientes
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Nueva configuracion para la aplicacion Next.js
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_clientes
    ports:
      - "3000:3000"
    environment:
      # Sobrescribimos la variable para que apunte al contenedor de base de datos, no a localhost
      - DATABASE_URL=postgresql://root:rootpassword@postgres:5432/db_clientes?schema=public
      - JWT_SECRET=nfwBqMFszntxAKHDnIkBOE+ns+/L0gwmQQNvAjAwEtU=
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge