

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_clientes
    environment:
      # la BD nace con las variables del env local
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Configuracion para la aplicacion Next.js
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_clientes
    ports:
      - "3000:3000"
    environment:
      # Inyectamos las variables
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge